config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users

  resources :islands do
    resources :bookings, only: [ :new, :create ]
  end

  get "user/islands", to: "islands#index_user"
  get "user/bookings", to: "bookings#index_user"

  resources :booking do
    member do
      patch "accept", to: "bookings#accept"
      patch "refuse", to: "bookings#refuse"
      patch "cancel", to: "bookings#cancel"
    end
  end


  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end
  
  mount StripeEvent::Engine, at: '/stripe-webhooks'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :island
  has_one :order
  has_one :notification, dependent: :destroy

  validates :start_date, presence: true
  validates :end_date, presence: true

  def total_price
    (end_date - start_date).to_i * island.price_per_day
  end
end

app/models/island.rb
class Island < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many_attached :photos
  has_many :orders
  monetize :price_per_day_cents

  validates :name, presence: true, uniqueness: true
  validates :country, :description, :latitude, :longitude, :price_per_day, :area, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_name_country_or_price_per_day,
    against: [:name, :country, :price_per_day],
    using: {
      tsearch: { prefix: true }
  }
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :booking

  def self.number_unread(current_user)
    count_islands_notif_unread(current_user) + count_bookings_notif_unread(current_user)
  end

  private

  def self.count_islands_notif_unread(current_user)
    @count_islands_notif = 0
    islands = current_user.islands
    islands.each do |island|
      island.bookings.each do |booking|
        unless booking.notification.owner_answer
          @count_islands_notif += 1
        end
      end
    end
    return @count_islands_notif
  end

  def self.count_bookings_notif_unread(current_user)
    Notification.where(user: current_user, to_read: true).count 
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :booking
  monetize :amount_cents
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :islands
  has_many :bookings
  has_many :orders
  has_many :notifications

  has_one_attached :avatar

  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :check_notifications

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :avatar])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :avatar])
  end

  private

  def check_notifications
    if user_signed_in?
      @count = Notification.number_unread(current_user)
    end
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index_user
    @user_bookings = current_user.bookings
    @all_islands_bookings = []
    current_user.islands.each { |island| island.bookings.each { |booking| @all_islands_bookings << booking } }
    current_user.notifications.each { |notif| notif.update(to_read: false) }
  end

  def new
    @booking = Booking.new
    @island = Island.find(params[:island_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @island = Island.find(params[:island_id])
    @booking.user = current_user
    @booking.island = @island
    @notification = Notification.new()
    @notification.user = current_user
    @notification.booking = @booking
    if @booking.save
      @notification.save
      redirect_to user_bookings_path, notice: "Booking made successfully"
    else
      render :new
    end
  end
  
  def accept
    @booking = Booking.find(params[:id])
    @booking.update(state: "Accepted")
    @booking.notification.update(owner_answer: true, to_read: true)
    redirect_to user_bookings_path, notice: "Booking Accepted!"
  end
  
  def refuse
    @booking = Booking.find(params[:id])
    @booking.update(state: "Refused")
    @booking.notification.update(owner_answer: true, to_read: true)
    redirect_to user_bookings_path, notice: "Booking Refused!"
  end

  def cancel
    @booking = Booking.find(params[:id])
    @booking.update(state: "Canceled")
    @booking.notification.update(owner_answer: true)
    redirect_to user_bookings_path, notice: "Booking Canceled!"
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :state)
  end

end

app/controllers/islands_controller.rb
class IslandsController < ApplicationController
  before_action :find_island, only: [:edit, :update, :show, :destroy]

  def index
    if params[:query].present?
      @islands = Island.search_by_name_country_or_price_per_day(params[:query])
      @islands_all = Island.all

      if @islands.empty?
        @markers = markers(@islands_all)
      else
        @markers = markers(@islands)
      end

    else
      @islands = Island.all
      @markers = markers(@islands)
    end
  end

  def show
    @booking = Booking.new
  end

  def new
    @island = Island.new
  end

  def create
    @island = Island.new(island_params)
    @island.user = current_user
    if @island.save
      redirect_to island_path(@island), notice: "Island was successfully created"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @island.update(island_params)
      redirect_to user_islands_path, notice: "Island was successfully updated"
    else
      render :edit
    end
  end

  def destroy
    @island.destroy
    if current_user.islands != []
      redirect_to user_islands_path, notice: "Island was successfully deleted"
    else
      redirect_to root_path, notice: "Island was successfully deleted"
    end
  end

  def index_user
    @user_islands = current_user.islands
  end

  private

  def find_island
    @island = Island.find(params[:id])
  end

  def island_params
    params.require(:island).permit(:name, :country, :description, :latitude, :longitude, :price_per_day, :area, photos: [])
  end

  def markers(islands)
    islands.map do |island|
      {
        lat: island.latitude,
        lng: island.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { island: island }),
        image_url: helpers.asset_url('missing_img')
      }
    end
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
  booking = Booking.find(params[:booking_id])
  order  = Order.create!(booking: booking, amount: booking.total_price, state: 'pending', user: current_user)
  session = Stripe::Checkout::Session.create(
    payment_method_types: ['card'],
    line_items: [{
      name: booking.island.name,
      amount: order.amount_cents,
      currency: 'usd',
      quantity: 1
    }],
    success_url: order_url(order),
    cancel_url: order_url(order)
  )

  order.update(checkout_session_id: session.id)
  redirect_to new_order_payment_path(order)
  end

  def show
    @order = current_user.orders.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    # @islands = Island.all.shuffle.take(3)
    @islands = Island.all.sort_by(&:id).take(12)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
    @order = current_user.orders.where(state: 'pending').find(params[:order_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index_user.html.erb
<div id="bookings-index" class="container">

  <% if current_user.islands != [] %>
    <div id="user-islands-bookings">
      <div class="user-bookings-header">
        <h3>My islands bookings</h3>
        <div class="user-bookings-selector">
          <div class="selector-name">Island :</div>
          <select class="select2" id="island-selector">
            <option value="all">All</option>
            <% current_user.islands.each do |island| %>
              <option value=<%= island.name %>><%= island.name %></option>
            <% end %>
          </select>
        </div>
        <div class="user-bookings-selector">
          <div class="selector-name">State :</div>
          <select class="select2" id="island-bookings-state">
            <option value="all">All</option>
            <option value="waiting">Waiting</option>
            <option value="accepted">Accepted</option>
            <option value="refused">Refused</option>
            <option value="canceled">Canceled</option>
          </select>
        </div>
      </div>
      <div id="user-islands-bookings-list">
        <% if @all_islands_bookings != [] %>
          <% @all_islands_bookings.sort_by(&:created_at).each do |booking| %>
            <div class="<%= "island-name island-#{booking.island.name.downcase}" %>" data-name=<%= "#{booking.island.name.downcase}" %>>
              <div class="island-booking <%= "booking-#{booking.state.downcase}" %>" data-state=<%= "#{booking.state.downcase}" %>>
                <div class="island-booking-content">
                  <div class="island-booking-left">
                    <div>
                      <%= booking.created_at %>
                      <br>
                      <strong><%= booking.user.username %></strong> has booked <strong><%= booking.island.name %></strong>
                      <br>
                      <i class="fas fa-calendar-alt"></i> from <%= booking.start_date %> to <%= booking.end_date %>
                    </div>
                  </div>
                  <div class="island-booking-center">
                    <div>
                      Length of stay : <%= (booking.end_date - booking.start_date).ceil %> days
                      <br>
                      <br>
                      Total price : <i class="fas fa-dollar-sign"></i> <%= (booking.end_date - booking.start_date).ceil * booking.island.price_per_day %>
                    </div>
                  </div>
                  <div class="island-booking-right">
                    <span class="<%= "booking-state-#{booking.state.downcase}" %>"><%= booking.state %></span>
                    <% if booking.state == "Waiting" %>
                      <%= link_to accept_booking_path(booking), method: :patch, title: 'Accept booking', data: { toggle: 'tooltip', confirm: "Are you sure?" }, class: "accept-booking" do %>
                        <i class="fas fa-check-circle"></i>
                      <% end %>
                      <%= link_to refuse_booking_path(booking), method: :patch, title: 'Refuse booking', data: { toggle: 'tooltip', confirm: "Are you sure?" }, class: "refuse-booking" do %>
                        <i class="fas fa-times-circle"></i>
                      <% end %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>

  <div id="user-bookings">
    <div class="user-bookings-header">
      <h3>My bookings</h3>
      <div class="user-bookings-selector">
        <div class="selector-name">State :</div>
        <select class="select2" id="user-bookings-state">
          <option value="all">All</option>
          <option value="waiting">Waiting</option>
          <option value="accepted">Accepted</option>
          <option value="refused">Refused</option>
          <option value="canceled">Canceled</option>
        </select>
      </div>
    </div>
    <% if current_user.bookings != [] %>
      <div id="user-bookings-list">
        <% @user_bookings.each do |booking| %>
          <div class="user-booking" data-state=<%= "#{booking.state.downcase}" %>>
            <div class="user-booking-content">
              <div class="user-booking-left">
                <div>
                  <h6>Booking for the island <strong><%= booking.island.name %></strong><br>
                  Owner : <strong><%= booking.island.user.username %></strong></h6>
                  <i class="fas fa-calendar-alt"></i> from <%= booking.start_date %> to <%= booking.end_date %>
                </div>
              </div>
              <div class="user-booking-center">
                <div>
                  Length of stay : <%= (booking.end_date - booking.start_date).ceil %> days
                  <br>
                  <br>
                  Total price : <i class="fas fa-dollar-sign"></i> <%= (booking.end_date - booking.start_date).ceil * booking.island.price_per_day %>
                  <br>
                </div>
              </div>
              <div class="user-booking-right">
                <span class="<%= "booking-state-#{booking.state.downcase}" %>"><%= booking.state %></span>
                <% if booking.state == "Waiting" %>
                  <%= link_to cancel_booking_path(booking), method: :patch, title: 'Cancel booking', data: { toggle: 'tooltip', confirm: "Are you sure?" }, class: "cancel-booking" do %>
                    <i class="fas fa-times-circle"></i>
                  <% end %>
                <%  elsif booking.state == "Accepted" %>
                  <% unless booking.order && booking.order.state == "paid"%>
                    <%= form_tag orders_path do %>
                      <%= hidden_field_tag 'booking_id', booking.id %>
                      <%= submit_tag 'Purchase', class: 'btn btn-purchase', id: 'purchase' %>
                    <% end %>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% else %>
      <p>You haven't made a booking yet</p>
    <% end %>
  </div>

</div>

app/views/bookings/new.html.erb
<div class="container">
  <%= simple_form_for([@island, @booking]) do |f| %>
    <%= f.input :start_date, as: :string, required: false, input_html: { id: "range_start" }  %>
    <%= f.input :end_date, as: :string, required: false, input_html: { id: "range_end" } %>
    <%= f.submit class: 'my-primary-btn', id: 'btn-submit' %>
  <% end %>
</div>

app/views/islands/_cards_index.html.erb
<% islands.each do |island| %>
  <div class="island-card">
    <%= link_to island_path(island) do %>
      <% if island.photos.attached?%>
        <%= cl_image_tag island.photos[0].key, class: "island-picture" %>
      <% else %>
        <%= image_tag "missing_img.jpg", class: "island-picture" %>
      <% end %>
    <% end %>
    <div class="info">
      <h5><%= island.name %> - <span class="country-name"><%= island.country %><i class="country-flag"></i></span></h5>
      <h6> <strong><%= island.price_per_day %></strong>/ day</h6>
    </div>
  </div>
<% end %>

app/views/islands/_form.html.erb
<div id="form-container">
  <div class="container">
    <div class="d-flex">
      <div class="form col-4" id="info">
        <%= simple_form_for(island) do |f| %>
          <%= f.input :name %>
          <%= f.input :country %>
          <%= f.input :longitude %>
          <%= f.input :latitude %>
          <%= f.input :area %>
          <%= f.input :price_per_day %>
          <%= f.input :photo, as: :file %>
          <%= f.submit "Submit", class: "btn btn-primary" %>
        <% end %>
      </div>

      <div class="form col-8" id="description">
        <%= simple_form_for(island) do |f| %>
          <%= f.input :description, as: :text %>
        <% end %>
      </div>

    </div>

  </div>
</div>

app/views/islands/_info_window.html.erb
<div class="pop-up">
  <h2><%= island.name %> - <%= island.country %></h2>
  <br>
  <% if island.photos.attached? %>
    <%= cl_image_tag island.photos[0].key, class: "pop-up-image" %>
  <% else %>
    <%= image_tag "missing_img.jpg", id: "image", class: "pop-up-image"%>
  <% end %>
</div>

app/views/islands/_island_card_index.html.erb
<% islands.each do |island| %>
  <div class="island-card">
    <%= link_to island_path(island), target: "_blank" do %>
      <% if island.photos.attached?%>
        <%= cl_image_tag island.photos[0].key, class: "island-picture" %>
      <% else %>
        <%= image_tag "missing_img.jpg", class: "island-picture" %>
      <% end %>
    <% end %>
    <div class="info">
      <h5><%= island.name %> - <span class="country-name"><%= island.country %><i class="country-flag"></i></span></h5>
      <h6> <strong><%= island.price_per_day %> $ </strong>/ day</h6>
    </div>
  </div>
<% end %>

app/views/islands/edit.html.erb
<div class="container">
  <%= render "shared/form", island: @island %>
</div>

app/views/islands/index.html.erb
<div class="row">
  <div class="col-sm-12 col-md-6 col-lg-7">
    <div class="index-title">
      <h1>Islands</h1>
      <%= render "shared/phone-searchbar" %>
    </div>
    <% if @islands.empty?%>
      <h2>Sorry this Island is not on the list</h2>
      <h4>Have a look at this</h4>
      <%= render "island_card_index", islands: @islands_all %>
    <% else %>
      <%= render "island_card_index", islands: @islands %>
    <% end %>
  </div>
  <div class="col-sm-12 col-md-6 col-lg-5">
    <div id="map"
         data-markers="<%= @markers.to_json %>"
         data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

app/views/islands/index_user.html.erb
<div class="container pt-3 mb-3">
  <h1>My islands</h1>
  <% @user_islands.each do |island| %>
    <div class="user-island-card">
      <div class="user-island-card-top">
        <div class="user-island-card-img">
          <% if island.photos.attached? %>
            <%= cl_image_tag island.photos[0].key %>
          <% else %>
            <%= image_tag "missing_img.jpg" %>
          <% end %>
        </div>
        <div class="user-island-card-content">
          <h2><%= island.name %></h2>
          <h4 class="country-name"><%= island.country %><span class="country-flag"></span></h4>
          <%= link_to "<i class='fas fa-pencil-alt'></i>".html_safe, edit_island_path(island), class: "user-island-card-edit", title: 'Edit', data: { toggle: 'tooltip' } %>
          <i class="fas fa-trash-alt user-island-card-delete sweet-alert-warning", title='Delete', data-toggle='tooltip', data-id=<%= "#{island.id}" %>></i>
          <%= link_to "", island_path(island), method: :delete, class: "hidden", id: "#{island.id}" %>
          <span class="user-island-card-location"><i class="fas fa-compass"></i> <%= island.latitude %>, <%= island.longitude %></span>
          <span class="user-island-card-area"><i class="fas fa-chart-area"></i> <%= island.area %> km²</span>
          <span class="user-island-card-price"><i class="fas fa-dollar-sign"></i><%= island.price_per_day %> / Day</span>
        </div>
      </div>
      <div class="user-island-card-bottom">
        <p><%= island.description %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/islands/new.html.erb
<div class="container">
  <%= render "shared/form", island: @island %>
</div>

app/views/islands/show.html.erb
<div id="show-island-container">
  <div id="show-island-images">
    <div id="show-island-image-big">
    <h1><%= @island.name %></h1>
      <span id="big-img", data-state="0">
        <% if @island.photos.attached?%>
          <%= cl_image_tag @island.photos[0].key %>
        <% else %>
          <%= image_tag "missing_img"%>
        <% end %>
      </span>
    </div>

    <div id="show-island-images-small">
        <div class="show-island-image-small-container">
          <span class="small-img">
            <% if @island.photos[1] != nil %>
              <%= cl_image_tag @island.photos[1].key %>
            <% else %>
              <%= image_tag "missing_img"%>
            <% end %>
          </span>
        </div>
        <div class="show-island-image-small-container">
          <span class="small-img">
            <% if @island.photos[2] != nil %>
              <%= cl_image_tag @island.photos[2].key %>
            <% else %>
              <%= image_tag "missing_img"%>
            <% end %>
          </span>
        </div>
        <div class="show-island-image-small-container">
          <span class="small-img">
            <% if @island.photos[3] != nil %>
              <%= cl_image_tag @island.photos[3].key %>
            <% else %>
              <%= image_tag "missing_img"%>
            <% end %>
          </span>
        </div>
        <div class="show-island-image-small-container">
          <span class="small-img">
            <% if @island.photos[4] != nil %>
              <%= cl_image_tag @island.photos[4].key %>
            <% else %>
              <%= image_tag "missing_img"%>
            <% end %>
          </span>
        </div>
    </div>
  </div>

  <div id="show-island-infos-container">
    <div id="show-island-infos">
      <h4><%= @island.name %> - <span class="country-name"><%= @island.country %><i class="country-flag"></i></span></h4>
      <span>Owner: <strong><%= @island.user.username %></strong></span>
      <div id="show-island-infos-content">
        <%= @island.description %>
      </div>
      <div id="show-island-more-infos">
      More infos : <br>
      <i class="fas fa-chart-area"></i> <%= @island.area %> km²
      <br>
      <i class="fas fa-compass"></i> <%= @island.latitude %>, <%= @island.longitude %>
      </div>
    </div>
    <% if current_user != @island.user %>
      <div id="show-island-booking-form">
        <span>Select dates to see the price: <i class="fas fa-dollar-sign"> <%= @island.price_per_day %> / day</i></span>
        <%= simple_form_for([@island, @booking]) do |f| %>
          <div id="booking-form-dates">
            <%= f.input :start_date, as: :string, required: false, input_html: { id: "range_start" }  %>
            <%= f.input :end_date, as: :string, required: false, input_html: { id: "range_end" } %>
          </div>
          <div id="booking-form-bottom">
            <div id="booking-form-infos">
              Length of stay : <span id="length-of-stay"></span> days <br>
              Total price : <i class="fas fa-dollar-sign"></i> <strong><span id="total-price", data-price=<%= "#{@island.price_per_day}" %>></span></strong>
            </div>
            <%= f.submit id: 'btn-submit-booking' %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

</div>

app/views/orders/show.html.erb
<div class="container1 container">
  <%= link_to "Back", islands_path, class:"button back" %>
  <div class=" card-payement row py-4">
    <div class="col-md-3">
      <% if @order.booking.island.photos.attached? %>
          <%= cl_image_tag @order.booking.island.photos[0].key, class:"img-payement" %>
        <% else %>
          <%= image_tag "missing_img", class:"img-payement"%>
        <% end %>
    </div>
    <div class="col">
      <h1>Order <%= @order.id %> <small><span class="badge badge-primary"><%= @order.state %></span></small></h1>
      <ul class="list-unstyled">
        <li><strong>ISSUED ON</strong> <%= @order.created_at.to_date %></li>
        <li><strong>Island</strong> <%= @order.booking.island.name %> [<%= @order.booking.island.country %>]</li>
        <li><strong>TOTAL</strong> <%= humanized_money_with_symbol @order.amount %></li>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div id="banner">
    <div class="main-header">
      <h1>Rent an Island</h1>
      <p>Discover all the islands you nerver seen<p/>
      <%= link_to "Discover our Island",  islands_path, class: "btn-home-island" %>
    </div>
</div>
<div class="container my-4" id="galery">
  <div class="text-center">
    <h2>Have you ever dreamed of having your own island just for you?</h2>
    <br>
    <h3 class= "laptop-size">Our Beautiful Island</h3>
    <h4 class= "phone-size">Find The Island of Your <strong>Dream</strong> </h4>
    <%= render "shared/phone-searchbar" %>
  </div>
  <%# <div class="cards"> %>
    <%#= render "island_card_home", islands: @islands %>
  <%# </div> %>
</div>

<%= render "carousel", islands: @islands %>


<div class="row footer">
  <div class="col-sm-12 col-md-6 col-lg-5">
   <h2><%= image_tag("logo.png") %> Rent an Island</h2>
   <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    Donec placerat rutrum lectus vitae pharetra. Integer consectetur
    malesuada lorem consectetur volutpat. Sed vitae neque eros.
    Nulla mattis porttitor interdum.</p>
  </div>
  <div class="col-sm-12 col-md-6 col-lg-5">
    <div class="footer-follow-us">
    <h2>Follow US</h2>
    <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <div class="logo">
    <%= link_to "/", class: "navbar-brand", title: 'Home', data: { toggle: 'tooltip' } do %>
      <%= image_tag("logo.png")%>
    <% end %>
  </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <%= render "shared/searchbar" %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <% if user_signed_in? %>
      <div id="notifications-info">
        <% unless @count == 0 %>
          <span id="notif-count"><%= @count %></span>
        <% end %>
        <%= link_to "<i class='fas fa-bell'></i>".html_safe, user_bookings_path %>
      </div>
    <% end %>
    <%= link_to "Add your Island", new_island_path, class: "nav-link btn-navbar", id: "new-island-link" %>
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <% if current_user.avatar.attached? %>
            <%= cl_image_tag current_user.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <i class="fas fa-user-circle avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <% if current_user.islands != [] %>
              <%= link_to "My Islands", user_islands_path, class: "dropdown-item" %>
            <% end %>
            <%= link_to "Bookings", user_bookings_path, class: "dropdown-item" %>
            <%= link_to "Edit my account", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link btn-navbar", id: "login-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_phone-searchbar.html.erb
<%= form_tag islands_path, method: :get do %>
  <div class="phone-searchbar">
    <div class="form-outline">
      <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find an Island"
      %>
    </div>
    <button type="submit" class="btn btn-primary">
      <i class="fas fa-globe-europe globe-color"></i>
    </button>
  </div>
<% end %>

app/views/shared/_searchbar.html.erb
<%= form_tag islands_path, class:"laptop-searchbar", method: :get do %>
  <div class="laptop-searchbar">
    <div class="form-outline">
      <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find an Island"
      %>
    </div>
    <button type="submit" class="btn btn-primary">
      <i class="fas fa-globe-europe globe-color"></i>
    </button>
  </div>
<% end %>